# -*- coding: utf-8 -*-
"""Supervisor 路由关键词与模式常量。"""

from config.keyword_settings import (
    SUPERVISOR_AGENT_FAILURE_CONNECTION_MARKERS,
    SUPERVISOR_AGENT_FAILURE_TIMEOUT_MARKERS,
    SUPERVISOR_CLAUSE_CONNECTOR_PATTERNS,
    SUPERVISOR_CODE_ACTION_HINTS,
    SUPERVISOR_CODE_LANGUAGE_ONLY_MARKERS,
    SUPERVISOR_CODE_LEARNING_HINTS,
    SUPERVISOR_CODE_SNIPPET_PATTERNS,
    SUPERVISOR_KEYWORDS,
    SUPERVISOR_SEARCH_ACTION_HINTS,
    SUPERVISOR_SEARCH_GENERIC_QUERY_HINTS,
    SUPERVISOR_SEQUENTIAL_HINT_PAIRS,
    SUPERVISOR_SQL_EXPLICIT_ANCHORS,
    SUPERVISOR_SUMMARY_HINTS,
    SUPERVISOR_WEATHER_ACTION_PATTERNS,
    SupervisorKeywordGroup,
)

SUPERVISOR_HISTORY_YUNYOU_KEYWORDS = SUPERVISOR_KEYWORDS[SupervisorKeywordGroup.HISTORY_YUNYOU]
SUPERVISOR_HISTORY_SQL_KEYWORDS = SUPERVISOR_KEYWORDS[SupervisorKeywordGroup.HISTORY_SQL]
SUPERVISOR_HISTORY_WEATHER_KEYWORDS = SUPERVISOR_KEYWORDS[SupervisorKeywordGroup.HISTORY_WEATHER]
SUPERVISOR_HISTORY_WEATHER_FACT_KEYWORDS = SUPERVISOR_KEYWORDS[SupervisorKeywordGroup.HISTORY_WEATHER_FACT]
SUPERVISOR_HISTORY_SEARCH_KEYWORDS = SUPERVISOR_KEYWORDS[SupervisorKeywordGroup.HISTORY_SEARCH]

__all__ = [
    "SUPERVISOR_KEYWORDS",
    "SupervisorKeywordGroup",
    "SUPERVISOR_HISTORY_YUNYOU_KEYWORDS",
    "SUPERVISOR_HISTORY_SQL_KEYWORDS",
    "SUPERVISOR_HISTORY_WEATHER_KEYWORDS",
    "SUPERVISOR_HISTORY_WEATHER_FACT_KEYWORDS",
    "SUPERVISOR_HISTORY_SEARCH_KEYWORDS",
    "SUPERVISOR_SQL_EXPLICIT_ANCHORS",
    "SUPERVISOR_SEARCH_GENERIC_QUERY_HINTS",
    "SUPERVISOR_WEATHER_ACTION_PATTERNS",
    "SUPERVISOR_SEARCH_ACTION_HINTS",
    "SUPERVISOR_CODE_LEARNING_HINTS",
    "SUPERVISOR_CODE_ACTION_HINTS",
    "SUPERVISOR_CODE_SNIPPET_PATTERNS",
    "SUPERVISOR_CODE_LANGUAGE_ONLY_MARKERS",
    "SUPERVISOR_AGENT_FAILURE_TIMEOUT_MARKERS",
    "SUPERVISOR_AGENT_FAILURE_CONNECTION_MARKERS",
    "SUPERVISOR_SUMMARY_HINTS",
    "SUPERVISOR_SEQUENTIAL_HINT_PAIRS",
    "SUPERVISOR_CLAUSE_CONNECTOR_PATTERNS",
]
