# -*- coding: utf-8 -*-
from __future__ import annotations

from typing import Any, Callable, Dict, Optional, Protocol

from harness.types import RunContext, RunStateSnapshot


class CancellationManagerContract(Protocol):
    def register_request(self, request_id: str): ...
    def link_request(self, parent_request_id: str, child_request_id: str) -> None: ...
    def cancel_request(self, request_id: str) -> None: ...
    def cleanup_request(self, request_id: str) -> None: ...
    def is_cancelled(self, request_id: Optional[str] = None) -> bool: ...


class LiveStreamBusContract(Protocol):
    def register_callback(self, run_id: str, callback: Callable[[Dict[str, Any]], None]) -> None: ...
    def unregister_callback(self, run_id: str) -> None: ...
    def publish(self, run_id: str, agent_name: str, content: str) -> None: ...
    def has_streamed(self, run_id: str, agent_name: str) -> bool: ...


class RunStateStoreContract(Protocol):
    def register_run(self, run_context: RunContext) -> RunStateSnapshot: ...
    def record_workflow_event(self, run_id: str, payload: Dict[str, Any]) -> Optional[RunStateSnapshot]: ...
    def mark_status(self, run_id: str, status: str, **kwargs: Any) -> Optional[RunStateSnapshot]: ...
    def get(self, run_id: str) -> Optional[RunStateSnapshot]: ...
    def get_latest_for_session(self, session_id: str) -> Optional[RunStateSnapshot]: ...

